apiVersion: v1
kind: Secret
metadata:
  name: my-secret
type: Opaque
data:
  username: YWRtaW4=  # Base64 encoded value of 'admin'
  password: MWYyZDFlMmU2N2Rm  # Base64 encoded value of '1f2d1e2e67df'
